FROM php:8.3-apache
RUN docker-php-ext-install pdo_mysql && a2enmod rewrite
COPY tests/apache-vhost.conf /etc/apache2/sites-available/000-default.conf
RUN printf 'Listen 8081\n' > /etc/apache2/ports.conf
